"
"flazz/vim-colorschemes selections
"
callminpac#add('flazz/vim-colorschemes')
"
"colorscheme 0x7A69_dark
"colorscheme 1989
"colorscheme 256-gra
"colorscheme 256-jungle
"colorscheme 256_noir
"colorscheme 3dglasses
"colorscheme Atelier_CaveDark
"colorscheme Atelier_CaveLight
"colorscheme Atelier_DuneDark
"colorscheme Atelier_DuneLight
"colorscheme Atelier_EstuaryDark
"colorscheme Atelier_EstuaryLight
"colorscheme Atelier_ForestDark
"colorscheme Atelier_ForestLight
"colorscheme Atelier_HeathDark
"colorscheme Atelier_HeathLight
"colorscheme Atelier_LakesideDark
"colorscheme Atelier_LakesideLight
"colorscheme Atelier_PlateauDark
"colorscheme Atelier_PlateauLight
"colorscheme Atelier_SavannaDark
"colorscheme Atelier_SavannaLight
"colorscheme Atelier_SeasideDark
"colorscheme Atelier_SeasideLight
"colorscheme Atelier_SulphurpoolDark
"colorscheme Atelier_SulphurpoolLight
"colorscheme Benokai
"colorscheme Black
"colorscheme BlackSea
"colorscheme Blue2
"colorscheme C64
"colorscheme CandyPaper
"colorscheme Chasing_Logic
"colorscheme ChocolateLiquor
"colorscheme ChocolatePapaya
"colorscheme CodeFactoryv3
"colorscheme Dark
"colorscheme Dark2
"colorscheme DarkDefault
"colorscheme DevC++
"colorscheme Dev_Delight
"colorscheme Dim
"colorscheme Dim2
"colorscheme DimBlue
"colorscheme DimGreen
"colorscheme DimGreens
"colorscheme DimGrey
"colorscheme DimRed
"colorscheme DimSlate
"colorscheme Green
"colorscheme Light
"colorscheme LightDefault
"colorscheme LightDefaultGrey
"colorscheme LightTan
"colorscheme LightYellow
"colorscheme Monokai
"colorscheme MountainDew
"colorscheme OceanicNext
"colorscheme OceanicNextLight
"colorscheme PapayaWhip
"colorscheme PaperColor
"colorscheme PerfectDark
"colorscheme Red
"colorscheme Revolution
"colorscheme SerialExperimentsLain
"colorscheme Slate
"colorscheme SlateDark
"colorscheme Spink
"colorscheme SweetCandy
"colorscheme Tomorrow
"colorscheme Tomorrow-Night
"colorscheme Tomorrow-Night-Blue
"colorscheme Tomorrow-Night-Bright
"colorscheme Tomorrow-Night-Eighties
"colorscheme VIvid
"colorscheme White2
"colorscheme abbott
"colorscheme abra
"colorscheme abyss
"colorscheme adam
"colorscheme adaryn
"colorscheme adobe
"colorscheme adrian
"colorscheme advantage
"colorscheme adventurous
"colorscheme af
"colorscheme afterglow
"colorscheme aiseered
"colorscheme alduin
"colorscheme ancient
"colorscheme anderson
"colorscheme angr
"colorscheme anotherdark
"colorscheme ansi_blows
"colorscheme antares
"colorscheme apprentice
"colorscheme aqua
"colorscheme aquamarine
"colorscheme arcadia
"colorscheme archery
"colorscheme argonaut
"colorscheme ashen
"colorscheme asmanian2
"colorscheme asmanian_blood
"colorscheme asmdev
"colorscheme asmdev2
"colorscheme astronaut
"colorscheme asu1dark
"colorscheme atom
"colorscheme aurora
"colorscheme automation
"colorscheme autumn
"colorscheme autumnleaf
"colorscheme ayu
"colorscheme babymate256
"colorscheme badwolf
"colorscheme bandit
"colorscheme base
"colorscheme base16-ateliercave
"colorscheme base16-atelierdune
"colorscheme base16-atelierestuary
"colorscheme base16-atelierforest
"colorscheme base16-atelierheath
"colorscheme base16-atelierlakeside
"colorscheme base16-atelierplateau
"colorscheme base16-ateliersavanna
"colorscheme base16-atelierseaside
"colorscheme base16-ateliersulphurpool
"colorscheme base16-railscasts
"colorscheme basic
"colorscheme basic-dark
"colorscheme basic-light
"colorscheme bayQua
"colorscheme baycomb
"colorscheme bclear
"colorscheme beachcomber
"colorscheme beauty256
"colorscheme beekai
"colorscheme behelit
"colorscheme benlight
"colorscheme bensday
"colorscheme billw
"colorscheme biogoo
"colorscheme birds-of-paradise
"colorscheme bitterjug
"colorscheme black_angus
"colorscheme blackbeauty
"colorscheme blackboard
"colorscheme blackdust
"colorscheme blacklight
"colorscheme blaquemagick
"colorscheme blazer
"colorscheme blink
"colorscheme blue
"colorscheme bluechia
"colorscheme bluedrake
"colorscheme bluegreen
"colorscheme bluenes
"colorscheme blueprint
"colorscheme blues
"colorscheme blueshift
"colorscheme bluez
"colorscheme blugrine
"colorscheme bluish
"colorscheme bmichaelsen
"colorscheme boa
"colorscheme bocau
"colorscheme bog
"colorscheme boltzmann
"colorscheme borland
"colorscheme breeze
"colorscheme breezy
"colorscheme brighton
"colorscheme briofita
"colorscheme broduo
"colorscheme brogrammer
"colorscheme brookstream
"colorscheme brown
"colorscheme bubblegum
"colorscheme bubblegum-256-dark
"colorscheme bubblegum-256-light
"colorscheme buddy
"colorscheme burnttoast256
"colorscheme busierbee
"colorscheme busybee
"colorscheme buttercream
"colorscheme bvemu
"colorscheme bw
"colorscheme c
"colorscheme c16gui
"colorscheme cabin
"colorscheme cake
"colorscheme cake16
"colorscheme calmar256-dark
"colorscheme calmar256-light
"colorscheme camo
"colorscheme campfire
"colorscheme candy
"colorscheme candycode
"colorscheme candyman
"colorscheme caramel
"colorscheme carrot
"colorscheme carvedwood
"colorscheme carvedwoodcool
"colorscheme cascadia
"colorscheme celtics_away
"colorscheme cgpro
"colorscheme chalkboard
"colorscheme chance-of-storm
"colorscheme charged-256
"colorscheme charon
"colorscheme chela_light
"colorscheme cherryblossom
"colorscheme chlordane
"colorscheme chocolate
"colorscheme chroma
"colorscheme chrysoprase
"colorscheme clarity
"colorscheme cleanphp
"colorscheme cleanroom
"colorscheme clearance
"colorscheme cloudy
"colorscheme clue
"colorscheme cobalt
"colorscheme cobalt2
"colorscheme cobaltish
"colorscheme coda
"colorscheme codeblocks_dark
"colorscheme codeburn
"colorscheme codedark
"colorscheme codeschool
"colorscheme coffee
"colorscheme coldgreen
"colorscheme colorer
"colorscheme colorful
"colorscheme colorful256
"colorscheme colorsbox-faff
"colorscheme colorsbox-greenish
"colorscheme colorsbox-material
"colorscheme colorsbox-stblue
"colorscheme colorsbox-stbright
"colorscheme colorsbox-steighties
"colorscheme colorsbox-stnight
"colorscheme colorzone
"colorscheme contrastneed
"colorscheme contrasty
"colorscheme cool
"colorscheme corn
"colorscheme corporation
"colorscheme crayon
"colorscheme crt
"colorscheme crunchbang
"colorscheme cthulhian
"colorscheme custom
"colorscheme cyberpunk
"colorscheme d8g_01
"colorscheme d8g_02
"colorscheme d8g_03
"colorscheme d8g_04
"colorscheme dante
"colorscheme dark-ruby
"colorscheme darkZ
"colorscheme darkblack
"colorscheme darkblue
"colorscheme darkblue2
"colorscheme darkbone
"colorscheme darkburn
"colorscheme darkdevel
"colorscheme darkdot
"colorscheme darkeclipse
"colorscheme darker-robin
"colorscheme darkerdesert
"colorscheme darkglass
"colorscheme darkocean
"colorscheme darkrobot
"colorscheme darkslategray
"colorscheme darkspectrum
"colorscheme darktango
"colorscheme darkzen
"colorscheme darth
"colorscheme dawn
"colorscheme deep-space
"colorscheme deepsea
"colorscheme default
"colorscheme delek
"colorscheme delphi
"colorscheme denim
"colorscheme derefined
"colorscheme desert
"colorscheme desert256
"colorscheme desert256v2
"colorscheme desertEx
"colorscheme desertedocean
"colorscheme desertedoceanburnt
"colorscheme desertink
"colorscheme despacio
"colorscheme detailed
"colorscheme devbox-dark-256
"colorscheme deveiate
"colorscheme developer
"colorscheme diokai
"colorscheme disciple
"colorscheme distill
"colorscheme distinguished
"colorscheme django
"colorscheme donbass
"colorscheme donttouchme
"colorscheme doorhinge
"colorscheme doriath
"colorscheme dracula
"colorscheme dual
"colorscheme dull
"colorscheme duotone-dark
"colorscheme duotone-darkcave
"colorscheme duotone-darkdesert
"colorscheme duotone-darkearth
"colorscheme duotone-darkforest
"colorscheme duotone-darkheath
"colorscheme duotone-darklake
"colorscheme duotone-darkmeadow
"colorscheme duotone-darkpark
"colorscheme duotone-darkpool
"colorscheme duotone-darksea
"colorscheme duotone-darkspace
"colorscheme dusk
"colorscheme dw_blue
"colorscheme dw_cyan
"colorscheme dw_green
"colorscheme dw_orange
"colorscheme dw_purple
"colorscheme dw_red
"colorscheme dw_yellow
"colorscheme dzo
"colorscheme earendel
"colorscheme earth
"colorscheme earthburn
"colorscheme eclipse
"colorscheme eclm_wombat
"colorscheme ecostation
"colorscheme editplus
"colorscheme edo_sea
"colorscheme ego
"colorscheme eink
"colorscheme ekin
"colorscheme ekvoli
"colorscheme elda
"colorscheme eldar
"colorscheme elflord
"colorscheme elise
"colorscheme elisex
"colorscheme elrodeo
"colorscheme elrond
"colorscheme emacs
"colorscheme enigma
"colorscheme enzyme
"colorscheme erez
"colorscheme eva
"colorscheme eva01
"colorscheme eva01-LCL
"colorscheme evening
"colorscheme evening1
"colorscheme evokai
"colorscheme evolution
"colorscheme fahrenheit
"colorscheme fairyfloss
"colorscheme falcon
"colorscheme far
"colorscheme felipec
"colorscheme feral
"colorscheme fight-in-the-shade
"colorscheme fine_blue
"colorscheme firewatch
"colorscheme flatcolor
"colorscheme flatland
"colorscheme flatlandia
"colorscheme flattened_dark
"colorscheme flattened_light
"colorscheme flattown
"colorscheme flattr
"colorscheme flatui
"colorscheme fnaqevan
"colorscheme fog
"colorscheme fokus
"colorscheme forneus
"colorscheme freya
"colorscheme frood
"colorscheme frozen
"colorscheme fruidle
"colorscheme fruit
"colorscheme fruity
"colorscheme fu
"colorscheme fx
"colorscheme garden
"colorscheme gardener
"colorscheme gemcolors
"colorscheme genericdc
"colorscheme genericdc-light
"colorscheme gentooish
"colorscheme getafe
"colorscheme getfresh
"colorscheme ghostbuster
"colorscheme github
"colorscheme gobo
"colorscheme golded
"colorscheme golden
"colorscheme goldenrod
"colorscheme goodwolf
"colorscheme google
"colorscheme gor
"colorscheme gotham
"colorscheme gotham256
"colorscheme gothic
"colorscheme grape
"colorscheme gravity
"colorscheme grayorange
"colorscheme graywh
"colorscheme grb256
"colorscheme greens
"colorscheme greenvision
"colorscheme greenwint
"colorscheme grey2
"colorscheme greyblue
"colorscheme greygull
"colorscheme grishin
"colorscheme gruvbox
"colorscheme gryffin
"colorscheme guardian
"colorscheme guepardo
"colorscheme h80
"colorscheme habiLight
"colorscheme happy_hacking
"colorscheme harlequin
"colorscheme heliotrope
"colorscheme hemisu
"colorscheme herald
"colorscheme heroku
"colorscheme heroku-terminal
"colorscheme herokudoc
"colorscheme herokudoc-
"colorscheme hhazure
"colorscheme hhdblue
"colorscheme hhdcyan
"colorscheme hhdgray
"colorscheme hhdgreen
"colorscheme hhdmagenta
"colorscheme hhdred
"colorscheme hhdyellow
"colorscheme hhorange
"colorscheme hhpink
"colorscheme hhspring
"colorscheme hhteal
"colorscheme hhviolet
"colorscheme highlighter_term
"colorscheme highlighter_term_bright
"colorscheme highwayman
"colorscheme hilal
"colorscheme holokai
"colorscheme hornet
"colorscheme horseradish256
"colorscheme hotpot
"colorscheme hybrid
"colorscheme hybrid-light
"colorscheme hybrid_material
"colorscheme hybrid_reverse
"colorscheme hydrangea
"colorscheme iangenzo
"colorscheme ibmedit
"colorscheme icansee
"colorscheme iceberg
"colorscheme immortals
"colorscheme impact
"colorscheme impactG
"colorscheme impactjs
"colorscheme industrial
"colorscheme industry
"colorscheme ingretu
"colorscheme inkpot
"colorscheme inori
"colorscheme ir_black
"colorscheme ironman
"colorscheme itg_flat
"colorscheme itg_flat_transparent
"colorscheme itsasoa
"colorscheme jaime
"colorscheme jammy
"colorscheme janah
"colorscheme japanesque
"colorscheme jelleybeans
"colorscheme jellybeans
"colorscheme jellygrass
"colorscheme jellyx
"colorscheme jhdark
"colorscheme jhlight
"colorscheme jiks
"colorscheme jitterbug
"colorscheme kalahari
"colorscheme kalisi
"colorscheme kalt
"colorscheme kaltex
"colorscheme kate
"colorscheme kellys
"colorscheme khaki
"colorscheme kib_darktango
"colorscheme kib_plastic
"colorscheme kings-away
"colorscheme kiss
"colorscheme kkruby
"colorscheme koehler
"colorscheme kolor
"colorscheme kruby
"colorscheme kyle
"colorscheme laederon
"colorscheme lakers_away
"colorscheme landscape
"colorscheme lanox
"colorscheme lanzarotta
"colorscheme lapis256
"colorscheme last256
"colorscheme late_evening
"colorscheme lazarus
"colorscheme legiblelight
"colorscheme leglight2
"colorscheme leo
"colorscheme less
"colorscheme lettuce
"colorscheme leya
"colorscheme lightcolors
"colorscheme lightning
"colorscheme lilac
"colorscheme lilydjwg_dark
"colorscheme lilydjwg_green
"colorscheme lilypink
"colorscheme lingodirector
"colorscheme liquidcarbon
"colorscheme literal_tango
"colorscheme lizard
"colorscheme lizard256
"colorscheme lodestone
"colorscheme loogica
"colorscheme louver
"colorscheme lucid
"colorscheme lucius
"colorscheme luinnar
"colorscheme lumberjack
"colorscheme luna
"colorscheme luna-term
"colorscheme lxvc
"colorscheme lyla
"colorscheme mac_classic
"colorscheme macvim-light
"colorscheme made_of_code
"colorscheme madeofcode
"colorscheme magellan
"colorscheme magicwb
"colorscheme mango
"colorscheme manuscript
"colorscheme manxome
"colorscheme marklar
"colorscheme maroloccio
"colorscheme maroloccio2
"colorscheme maroloccio3
"colorscheme mars
"colorscheme martin_krischik
"colorscheme material
"colorscheme material-theme
"colorscheme materialbox
"colorscheme materialtheme
"colorscheme matrix
"colorscheme maui
"colorscheme mayansmoke
"colorscheme mdark
"colorscheme mellow
"colorscheme messy
"colorscheme meta5
"colorscheme metacosm
"colorscheme midnight
"colorscheme miko
"colorscheme minimal
"colorscheme minimalist
"colorscheme mint
"colorscheme mizore
"colorscheme mod8
"colorscheme mod_tcsoft
"colorscheme mohammad
"colorscheme mojave
"colorscheme molokai
"colorscheme molokai_dark
"colorscheme monoacc
"colorscheme monochrome
"colorscheme monokai-chris
"colorscheme monokai-phoenix
"colorscheme monokain
"colorscheme montz
"colorscheme moody
"colorscheme moonshine
"colorscheme moonshine_lowcontrast
"colorscheme moonshine_minimal
"colorscheme mophiaDark
"colorscheme mophiaSmoke
"colorscheme mopkai
"colorscheme more
"colorscheme moria
"colorscheme moriarty
"colorscheme morning
"colorscheme moss
"colorscheme motus
"colorscheme mourning
"colorscheme mrkn256
"colorscheme mrpink
"colorscheme mud
"colorscheme muon
"colorscheme murphy
"colorscheme mushroom
"colorscheme mustang
"colorscheme mythos
"colorscheme native
"colorscheme nature
"colorscheme navajo
"colorscheme navajo-night
"colorscheme nazca
"colorscheme nedit
"colorscheme nedit2
"colorscheme nefertiti
"colorscheme neodark
"colorscheme neon
"colorscheme neonwave
"colorscheme nerv-ous
"colorscheme nes
"colorscheme nets-away
"colorscheme neuromancer
"colorscheme neutron
"colorscheme neverland
"colorscheme neverland-darker
"colorscheme neverland2
"colorscheme neverland2-darker
"colorscheme neverness
"colorscheme nevfn
"colorscheme new-railscasts
"colorscheme newspaper
"colorscheme newsprint
"colorscheme nicotine
"colorscheme night
"colorscheme nightVision
"colorscheme night_vision
"colorscheme nightflight
"colorscheme nightflight2
"colorscheme nightshade
"colorscheme nightshade_print
"colorscheme nightshimmer
"colorscheme nightsky
"colorscheme nightwish
"colorscheme no_quarter
"colorscheme noclown
"colorscheme nocturne
"colorscheme nofrils-acme
"colorscheme nofrils-dark
"colorscheme nofrils-light
"colorscheme nofrils-sepia
"colorscheme nord
"colorscheme nordisk
"colorscheme northland
"colorscheme northsky
"colorscheme norwaytoday
"colorscheme nour
"colorscheme nuvola
"colorscheme obsidian
"colorscheme obsidian2
"colorscheme oceanblack
"colorscheme oceanblack256
"colorscheme oceandeep
"colorscheme oceanlight
"colorscheme off
"colorscheme olive
"colorscheme onedark
"colorscheme orange
"colorscheme osx_like
"colorscheme otaku
"colorscheme oxeded
"colorscheme pablo
"colorscheme pacific
"colorscheme paintbox
"colorscheme paramount
"colorscheme parsec
"colorscheme peachpuff
"colorscheme peaksea
"colorscheme pencil
"colorscheme penultimate
"colorscheme peppers
"colorscheme perfect
"colorscheme petrel
"colorscheme pf_earth
"colorscheme phd
"colorscheme phoenix
"colorscheme phphaxor
"colorscheme phpx
"colorscheme pink
"colorscheme pixelmuerto
"colorscheme plasticine
"colorscheme playroom
"colorscheme pleasant
"colorscheme potts
"colorscheme predawn
"colorscheme preto
"colorscheme pride
"colorscheme primaries
"colorscheme primary
"colorscheme print_bw
"colorscheme prmths
"colorscheme professional
"colorscheme proton
"colorscheme ps_color
"colorscheme pspad
"colorscheme pt_black
"colorscheme putty
"colorscheme pw
"colorscheme py-darcula
"colorscheme pyte
"colorscheme python
"colorscheme quagmire
"colorscheme quantum
"colorscheme radicalgoodspeed
"colorscheme raggi
"colorscheme railscasts
"colorscheme rainbow_autumn
"colorscheme rainbow_fine_blue
"colorscheme rainbow_fruit
"colorscheme rainbow_night
"colorscheme rainbow_sea
"colorscheme rakr-light
"colorscheme random
"colorscheme rastafari
"colorscheme rcg_gui
"colorscheme rcg_term
"colorscheme rdark
"colorscheme rdark-terminal
"colorscheme redblack
"colorscheme redstring
"colorscheme refactor
"colorscheme relaxedgreen
"colorscheme reliable
"colorscheme reloaded
"colorscheme revolutions
"colorscheme robinhood
"colorscheme rockets-away
"colorscheme ron
"colorscheme rootwater
"colorscheme sadek1
"colorscheme sand
"colorscheme sandydune
"colorscheme satori
"colorscheme saturn
"colorscheme scheakur
"colorscheme scite
"colorscheme scooby
"colorscheme seagull
"colorscheme sean
"colorscheme seashell
"colorscheme seattle
"colorscheme selenitic
"colorscheme seoul
"colorscheme seoul256
"colorscheme seoul256-light
"colorscheme seti
"colorscheme settlemyer
"colorscheme sexy-railscasts
"colorscheme sf
"colorscheme shades-of-teal
"colorscheme shadesofamber
"colorscheme shine
"colorscheme shiny-white
"colorscheme shobogenzo
"colorscheme sialoquent
"colorscheme sienna
"colorscheme sierra
"colorscheme sift
"colorscheme silent
"colorscheme simple256
"colorscheme simple_b
"colorscheme simple_dark
"colorscheme simpleandfriendly
"colorscheme simplewhite
"colorscheme simplon
"colorscheme skittles_autumn
"colorscheme skittles_berry
"colorscheme skittles_dark
"colorscheme sky
"colorscheme slate2
"colorscheme smarties
"colorscheme smp
"colorscheme smpl
"colorscheme smyck
"colorscheme soda
"colorscheme softblue
"colorscheme softbluev2
"colorscheme softlight
"colorscheme sol
"colorscheme sol-term
"colorscheme solarized
"colorscheme solarized8_dark
"colorscheme solarized8_dark_flat
"colorscheme solarized8_dark_high
"colorscheme solarized8_dark_low
"colorscheme solarized8_light
"colorscheme solarized8_light_flat
"colorscheme solarized8_light_high
"colorscheme solarized8_light_low
"colorscheme sole
"colorscheme sonofobsidian
"colorscheme sonoma
"colorscheme sorcerer
"colorscheme soruby
"colorscheme soso
"colorscheme sourcerer
"colorscheme southernlights
"colorscheme southwest-fog
"colorscheme space-vim-dark
"colorscheme spacegray
"colorscheme spacemacs-theme
"colorscheme spartan
"colorscheme spectro
"colorscheme spiderhawk
"colorscheme spring
"colorscheme spring-night
"colorscheme sprinkles
"colorscheme spurs_away
"colorscheme srcery
"colorscheme srcery-drk
"colorscheme stackoverflow
"colorscheme stefan
"colorscheme stereokai
"colorscheme stingray
"colorscheme stonewashed-256
"colorscheme stonewashed-dark-256
"colorscheme stonewashed-dark-gui
"colorscheme stonewashed-gui
"colorscheme stormpetrel
"colorscheme strange
"colorscheme strawimodo
"colorscheme summerfruit
"colorscheme summerfruit256
"colorscheme sunburst
"colorscheme surveyor
"colorscheme swamplight
"colorscheme sweater
"colorscheme symfony
"colorscheme synic
"colorscheme synthwave
"colorscheme tabula
"colorscheme tango
"colorscheme tango-desert
"colorscheme tango-morning
"colorscheme tango2
"colorscheme tangoX
"colorscheme tangoshady
"colorscheme taqua
"colorscheme tatami
"colorscheme tayra
"colorscheme tchaba
"colorscheme tchaba2
"colorscheme tcsoft
"colorscheme telstar
"colorscheme tender
"colorscheme termschool
"colorscheme tesla
"colorscheme tetragrammaton
"colorscheme textmate16
"colorscheme thegoodluck
"colorscheme thermopylae
"colorscheme thestars
"colorscheme thor
"colorscheme thornbird
"colorscheme tibet
"colorscheme tidy
"colorscheme tigrana-256-dark
"colorscheme tigrana-256-light
"colorscheme tir_black
"colorscheme tolerable
"colorscheme tomatosoup
"colorscheme tony_light
"colorscheme toothpik
"colorscheme torte
"colorscheme transparent
"colorscheme triplejelly
"colorscheme trivial256
"colorscheme trogdor
"colorscheme tropikos
"colorscheme true-monochrome
"colorscheme turbo
"colorscheme turtles
"colorscheme tutticolori
"colorscheme twilight
"colorscheme twilight256
"colorscheme twitchy
"colorscheme two-firewatch
"colorscheme two2tango
"colorscheme ubaryd
"colorscheme ubloh
"colorscheme umber-green
"colorscheme understated
"colorscheme underwater
"colorscheme underwater-mod
"colorscheme unicon
"colorscheme up
"colorscheme valloric
"colorscheme vanzan_color
"colorscheme vc
"colorscheme vcbc
"colorscheme vertLaiton
"colorscheme vexorian
"colorscheme vibrantink
"colorscheme vice
"colorscheme vilight
"colorscheme vim-material
"colorscheme vimbrains
"colorscheme vimbrant
"colorscheme vimicks
"colorscheme visualstudio
"colorscheme vividchalk
"colorscheme vj
"colorscheme void
"colorscheme vorange
"colorscheme vydark
"colorscheme vylight
"colorscheme wargrey
"colorscheme warm_grey
"colorscheme warriors-away
"colorscheme wasabi256
"colorscheme watermark
"colorscheme wellsokai
"colorscheme welpe
"colorscheme white
"colorscheme whitebox
"colorscheme whitedust
"colorscheme widower
"colorscheme wikipedia
"colorscheme win9xblueback
"colorscheme winter
"colorscheme winterd
"colorscheme wintersday
"colorscheme woju
"colorscheme wolfpack
"colorscheme wombat
"colorscheme wombat256
"colorscheme wombat256dave
"colorscheme wombat256i
"colorscheme wombat256mod
"colorscheme wood
"colorscheme wuye
"colorscheme wwdc16
"colorscheme wwdc17
"colorscheme xcode
"colorscheme xcode-default
"colorscheme xedit
"colorscheme xemacs
"colorscheme xian
"colorscheme xmaslights
"colorscheme xoria256
"colorscheme xterm16
"colorscheme yeller
"colorscheme zazen
"colorscheme zellner
"colorscheme zen
"colorscheme zenburn
"colorscheme zenesque
"colorscheme zephyr
"colorscheme zmrok
"colorscheme znake
